### PR TITLE
Prepare new release

### PR DESCRIPTION
**Pull request by phibos**
Prepare new release

### CODE REVIEW

**Comment by radoeka** [comment]
How long does it take, before a (the) new release shows up with 'pip'?
I just did a pip list --outdated, and it still list 1.3.0 as latest version.

**Comment by phibos** [comment]
Version 1.4.0 is available from PyPI see https://pypi.org/project/pelican-photos/#history

**Comment by phibos** [comment]
With Python 3.10.6
```
$ pip install pelican-photos==1.3.0
[...]
$ pip list --outdated              
Package        Version Latest Type
-------------- ------- ------ -----
pelican-photos 1.3.0   1.4.0  wheel
Pillow         8.4.0   9.2.0  wheel
pip            22.2.1  22.2.2 wheel
setuptools     63.2.0  65.3.0 wheel
```

**Comment by radoeka** [comment]
I tried again.  And again 1.3.0 is offered.  My python is 3.6.15, all requirements are satisfied so I assume that a python version > 3.6.x is needed for pelican-photos.  Could that be the case?

**Comment by phibos** [comment]
Because of CVE fixes we had to bump the pillow version >= 9.0.1 with #47 . But pillow has dropped Python 3.6 support in version 9.0.0 (See Changelog: https://github.com/python-pillow/Pillow/blob/main/CHANGES.rst#900-2022-01-02).

**Pull request merged**
